name: hacker_news
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  built_collection: '>=2.0.0 <5.0.0'
  built_value: ^6.1.5

  url_launcher: ^4.0.1

  http: ^0.11.3

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  build_runner: ^1.0.0
  built_value_generator: ^6.1.4

  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
